# Generated by Django 5.2 on 2025-05-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
