# Generated by Django 5.2 on 2025-05-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feedback_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='video',
        ),
    ]
